=== dyanet/osrs/osrs-api/src/main/resources/ops.dtd
<!--
Opensrs Protocol Suite (OPS) v 0.1
(C) Copyright 2000, Tucows Inc.
All Rights Reserved
OPS Message Definition
-->
<!-- Envelope -->
<!ELEMENT OPS_envelope (header,body)>
<!-- header part -->
<!ELEMENT header (version)>
<!-- body part -->
<!ELEMENT body (data_block)>
<!-- data block -->
<!ELEMENT data_block (dt_assoc | dt_array |
dt_scalar| dt_scalarref)>
<!-- data types -->
<!ELEMENT dt_assoc (dt_assoc | dt_array|
dt_scalar | dt_scalarref|
(item)*)>
<!ELEMENT dt_array (dt_assoc | dt_array |
dt_scalar | dt_scalarref |
(item)*)>
<!ELEMENT dt_scalar (#PCDATA | dt_assoc | dt_array |
dt_scalar | dt_scalarref)*>
<!ELEMENT dt_scalarref (#PCDATA | dt_assoc | dt_array |
dt_scalar | dt_scalarref)*>
<!ELEMENT item (#PCDATA |
dt_assoc | dt_array |
dt_scalar | dt_scalarref)*>
<!ATTLIST item
key CDATA #REQUIRED
class CDATA #IMPLIED >
<!ELEMENT version (#PCDATA)>
<!-- document information entities -->
<!ENTITY company 'Tucows'>
<!ENTITY copyright '2000, Tucows'>

=== dyanet/osrs/osrs-domains/src/test/resources/fixtures/belongs-to-rsp-reply.xml
<?xml version='1.0' encoding='UTF-8' standalone='no' ?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
<OPS_envelope>
 <header>
  <version>0.9</version>
 </header>
 <body>
  <data_block>
   <dt_assoc>
    <item key="protocol">XCP</item>
    <item key="object">DOMAIN</item>
    <item key="action">REPLY</item>
    <item key="attributes">
     <dt_assoc>
      <item key="belongs_to_rsp">1</item>
      <item key="domain_expdate">2023-11-01 00:49:10</item>
     </dt_assoc>
    </item>
    <item key="is_success">1</item>
    <item key="response_code">200</item>
    <item key="response_text">Query successful</item>
   </dt_assoc>
  </data_block>
 </body>
</OPS_envelope>

=== dyanet/osrs/osrs-api/src/test/resources/fixtures/name-suggest-reply.xml
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
<OPS_envelope>
  <header><version>0.9</version></header>
  <body>
    <data_block>
      <dt_assoc>
        <item key="protocol">XCP</item>
        <item key="action">REPLY</item>
        <item key="response_text">Command completed successfully</item>
        <item key="response_code">200</item>
        <item key="is_success">1</item>
        <item key="is_search_completed">1</item>
        <item key="attributes">
          <dt_assoc>
            <item key="lookup">
              <dt_assoc>
                <item key="count">2</item>
                <item key="is_success">1</item>
                <item key="response_code">200</item>
                <item key="items">
                  <dt_array>
                    <item key="0">
                      <dt_assoc>
                        <item key="domain">example.com</item>
                        <item key="status">taken</item>
                      </dt_assoc>
                    </item>
                    <item key="1">
                      <dt_assoc>
                        <item key="domain">example.net</item>
                        <item key="status">available</item>
                      </dt_assoc>
                    </item>
                  </dt_array>
                </item>
              </dt_assoc>
            </item>
            <item key="suggestion">
              <dt_assoc>
                <item key="count">5</item>
                <item key="is_success">1</item>
                <item key="response_code">200</item>
                <item key="items">
                  <dt_array>
                    <item key="0">
                      <dt_assoc>
                        <item key="domain">myexample.com</item>
                        <item key="status">available</item>
                      </dt_assoc>
                    </item>
                  </dt_array>
                </item>
              </dt_assoc>
            </item>
          </dt_assoc>
        </item>
      </dt_assoc>
    </data_block>
  </body>
</OPS_envelope>

=== dyanet/osrs/osrs-api/src/test/resources/fixtures/get-balance-reply.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
<OPS_envelope>
  <header>
    <version>0.9</version>
  </header>
  <body>
    <data_block>
      <dt_assoc>
        <item key="protocol">XCP</item>
        <item key="object">DOMAIN</item>
        <item key="action">REPLY</item>
        <item key="is_success">1</item>
        <item key="attributes">
          <dt_assoc>
            <item key="balance">9000.01</item>
            <item key="hold_balance">0.00</item>
          </dt_assoc>
        </item>
        <item key="response_code">200</item>
        <item key="response_text">Command successful</item>
      </dt_assoc>
    </data_block>
  </body>
</OPS_envelope>

=== dyanet/osrs/osrs-domains/src/test/resources/fixtures/get-deleted-domains-reply.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE OPS_envelope SYSTEM 'ops.dtd'>
<OPS_envelope>
  <header><version>0.9</version></header>
  <body>
    <data_block>
      <dt_assoc>
        <item key="protocol">XCP</item>
        <item key="object">DOMAIN</item>
        <item key="action">REPLY</item>
        <item key="is_success">1</item>
        <item key="attributes">
          <dt_assoc>
            <item key="page">1</item>
            <item key="page_size">40</item>
            <item key="total">3</item>
            <item key="del_domains">
              <dt_array>
                <item key="0">
                  <dt_assoc>
                    <item key="name">example1.com</item>
                    <item key="delete_date">01-MAR-2021 12:08:11</item>
                    <item key="delete_date_epoch">1614618491</item>
                    <item key="expiredate">01-MAR-2022 17:07:17</item>
                    <item key="expiredate_epoch">1646172437</item>
                    <item key="reason">By-Request</item>
                  </dt_assoc>
                </item>
              </dt_array>
            </item>
          </dt_assoc>
        </item>
        <item key="response_code">200</item>
        <item key="response_text">Command successful</item>
      </dt_assoc>
    </data_block>
  </body>
</OPS_envelope>
